export const applicantFormFields = [
  {
    id: 'username',
    htmlFor: 'username',
    label: 'Full Name',
    type: 'text',
    placeholder: 'Enter your full name',
    star: true,
  },
  {
    id: 'phoneNo',
    htmlFor: 'phoneNo',
    label: 'Phone Number',
    type: 'number',
    placeholder: 'Enter your phone number',
    star: true,
  },
  {
    id: 'email',
    htmlFor: 'email',
    label: 'Email Address',
    type: 'email',
    placeholder: 'Enter your email address',
    star: true,
  },
  {
    id: 'references',
    htmlFor: 'references',
    label: 'References (Optional)',
    type: 'text',
    placeholder: 'Enter any references',
    star: false,
  },
  {
    id: 'technology',
    htmlFor: 'technology',
    label: 'Technology',
    type: 'select',
    placeholder: 'Select technology',
    options: [
      'React',
      'Angular',
      'Vue',
      'Next.js',
      'Node.js',
      'Python',
      'Java',
      'Other',
    ],
    star: true,
  },
  {
    id: 'position',
    htmlFor: 'position',
    label: 'Applied Position',
    type: 'select',
    placeholder: 'Select Position',
    options: [
      'Full Stack Engineer',
      'Frontend Engineer',
      'Backend Engineer',
      'AI/ML Engineer',
      'Devops Engineer',
      'UI/UX Designer',
    ],
    star: true,
  },
  {
    id: 'salary',
    htmlFor: 'salary',
    label: 'Expected Salary',
    type: 'text',
    placeholder: 'Enter your salary expectation',
    star: true,
  },
  {
    id: 'level',
    htmlFor: 'level',
    label: 'Experience Level',
    type: 'select',
    placeholder: 'Select your experience level',
    options: ['Intern', 'Junior', 'Intermediate', 'Senior'],
    star: true,
  },
  {
    id: 'experience',
    htmlFor: 'experience',
    label: 'Years of Experience',
    type: 'select',
    placeholder: 'Select years of experience',
    options: ['0-1', '1-3', '3-5', '5-10', '10+'],
    star: true,
  },
];

export const RoleFilter = [
  'Full Stack Engineer',
  'Frontend Engineer',
  'Backend Engineer',
  'Devops Engineer',
  'UI/UX Designeer',
  'AI/ML Engineer',
  'Data Scientist',
];

export const LevelFilter = ['Intern', 'Junior', 'Intermediate', 'Senior'];
