export const applicantFormFields = [
  {
    id: 'username',
    htmlFor: 'username',
    label: 'Full Name',
    type: 'text',
    placeholder: 'Enter your full name',
  },
  {
    id: 'phoneNo',
    htmlFor: 'phoneNo',
    label: 'Phone Number',
    type: 'number',
    placeholder: 'Enter your phone number',
  },
  {
    id: 'email',
    htmlFor: 'email',
    label: 'Email Address',
    type: 'email',
    placeholder: 'Enter your email address',
  },
  {
    id: 'references',
    htmlFor: 'references',
    label: 'References (Optional)',
    type: 'text',
    placeholder: 'Enter any references',
  },
  {
    id: 'technology',
    htmlFor: 'technology',
    label: 'Technology',
    type: 'select',
    placeholder: 'Select technology',
    options: [
      'React',
      'Angular',
      'Vue',
      'Next.js',
      'Node.js',
      'Python',
      'Java',
      'Other',
    ],
  },
  {
    id: 'position',
    htmlFor: 'position',
    label: 'Applied Position',
    type: 'select',
    placeholder: 'Select Position',
    options: [
      'Full Stack Engineer',
      'Frontend Engineer',
      'Backend Engineer',
      'AI/ML Engineer',
      'Data Scientist',
      'UI/UX Designer',
    ],
  },
  {
    id: 'salary',
    htmlFor: 'salary',
    label: 'Expected Salary',
    type: 'text',
    placeholder: 'Enter your salary expectation',
  },
  {
    id: 'level',
    htmlFor: 'level',
    label: 'Experience Level',
    type: 'select',
    placeholder: 'Select your experience level',
    options: ['Intern', 'Junior', 'Intermediate', 'Senior'],
  },
  {
    id: 'experience',
    htmlFor: 'experience',
    label: 'Years of Experience',
    type: 'select',
    placeholder: 'Select years of experience',
    options: ['0-1', '1-3', '3-5', '5-10', '10+'],
  },
];
