export const tableData = [
  {
    applicant_name: "Sushank Gurung",
    applied_position: "React Developer",
    applicant_status: "Pending",
    tech_stack: "React, JavaScript, CSS",
    applicant_email: "sushank@gmail.com",
    applicant_phone_number: "12456789",
    applicant_experience: "2 years",
    applicant_experience_level: "Mid",
    expected_salary: "$1000",
    references: "John Doe",
  },
  {
    applicant_name: "Aryan Shrestha",
    applied_position: "Digital Marketing",
    applicant_status: "Interview Scheduled",
    tech_stack: "SEO, Google Ads",
    applicant_email: "aryan@gmail.com",
    applicant_phone_number: "12456789",
    applicant_experience: "1 year",
    applicant_experience_level: "Junior",
    expected_salary: "$800",
    references: "Jane Smith",
  },
  {
    applicant_name: "Alex Maharjan",
    applied_position: "MCdonnels Worker",
    applicant_status: "Rejected",
    tech_stack: "Customer Service",
    applicant_email: "alex@gmail.com",
    applicant_phone_number: "12456789",
    applicant_experience: "6 months",
    applicant_experience_level: "Entry",
    expected_salary: "$500",
    references: "Restaurant Manager",
  },
  {
    applicant_name: "Binit Maharjan",
    applied_position: "Junior Frontend Developer",
    applicant_status: "Hired",
    tech_stack: "HTML, CSS, JavaScript",
    applicant_email: "binit@gmail.com",
    applicant_phone_number: "123456789",
    applicant_experience: "1.5 years",
    applicant_experience_level: "Junior",
    expected_salary: "$900",
    references: "Team Lead",
  },
  {
    applicant_name: "Sushank Gurung",
    applied_position: "React Developer",
    applicant_status: "Pending",
    tech_stack: "React, JavaScript, CSS",
    applicant_email: "sushank@gmail.com",
    applicant_phone_number: "12456789",
    applicant_experience: "2 years",
    applicant_experience_level: "Mid",
    expected_salary: "$1000",
    references: "John Doe",
  },
  {
    applicant_name: "Aryan Shrestha",
    applied_position: "Digital Marketing",
    applicant_status: "Interview Scheduled",
    tech_stack: "SEO, Google Ads",
    applicant_email: "aryan@gmail.com",
    applicant_phone_number: "12456789",
    applicant_experience: "1 year",
    applicant_experience_level: "Junior",
    expected_salary: "$800",
    references: "Jane Smith",
  },
  {
    applicant_name: "Alex Maharjan",
    applied_position: "MCdonnels Worker",
    applicant_status: "Rejected",
    tech_stack: "Customer Service",
    applicant_email: "alex@gmail.com",
    applicant_phone_number: "12456789",
    applicant_experience: "6 months",
    applicant_experience_level: "Entry",
    expected_salary: "$500",
    references: "Restaurant Manager",
  },
  {
    applicant_name: "Binit Maharjan",
    applied_position: "Junior Frontend Developer",
    applicant_status: "Hired",
    tech_stack: "HTML, CSS, JavaScript",
    applicant_email: "binit@gmail.com",
    applicant_phone_number: "123456789",
    applicant_experience: "1.5 years",
    applicant_experience_level: "Junior",
    expected_salary: "$900",
    references: "Team Lead",
  },
  {
    applicant_name: "Sushank Gurung",
    applied_position: "React Developer",
    applicant_status: "Pending",
    tech_stack: "React, JavaScript, CSS",
    applicant_email: "sushank@gmail.com",
    applicant_phone_number: "12456789",
    applicant_experience: "2 years",
    applicant_experience_level: "Mid",
    expected_salary: "$1000",
    references: "John Doe",
  },
  {
    applicant_name: "Aryan Shrestha",
    applied_position: "Digital Marketing",
    applicant_status: "Interview Scheduled",
    tech_stack: "SEO, Google Ads",
    applicant_email: "aryan@gmail.com",
    applicant_phone_number: "12456789",
    applicant_experience: "1 year",
    applicant_experience_level: "Junior",
    expected_salary: "$800",
    references: "Jane Smith",
  },
  {
    applicant_name: "Alex Maharjan",
    applied_position: "MCdonnels Worker",
    applicant_status: "Rejected",
    tech_stack: "Customer Service",
    applicant_email: "alex@gmail.com",
    applicant_phone_number: "12456789",
    applicant_experience: "6 months",
    applicant_experience_level: "Entry",
    expected_salary: "$500",
    references: "Restaurant Manager",
  },
  {
    applicant_name: "Binit Maharjan",
    applied_position: "Junior Frontend Developer",
    applicant_status: "Hired",
    tech_stack: "HTML, CSS, JavaScript",
    applicant_email: "binit@gmail.com",
    applicant_phone_number: "123456789",
    applicant_experience: "1.5 years",
    applicant_experience_level: "Junior",
    expected_salary: "$900",
    references: "Team Lead",
  },
  {
    applicant_name: "Sushank Gurung",
    applied_position: "React Developer",
    applicant_status: "Pending",
    tech_stack: "React, JavaScript, CSS",
    applicant_email: "sushank@gmail.com",
    applicant_phone_number: "12456789",
    applicant_experience: "2 years",
    applicant_experience_level: "Mid",
    expected_salary: "$1000",
    references: "John Doe",
  },
  {
    applicant_name: "Aryan Shrestha",
    applied_position: "Digital Marketing",
    applicant_status: "Interview Scheduled",
    tech_stack: "SEO, Google Ads",
    applicant_email: "aryan@gmail.com",
    applicant_phone_number: "12456789",
    applicant_experience: "1 year",
    applicant_experience_level: "Junior",
    expected_salary: "$800",
    references: "Jane Smith",
  },
  {
    applicant_name: "Alex Maharjan",
    applied_position: "MCdonnels Worker",
    applicant_status: "Rejected",
    tech_stack: "Customer Service",
    applicant_email: "alex@gmail.com",
    applicant_phone_number: "12456789",
    applicant_experience: "6 months",
    applicant_experience_level: "Entry",
    expected_salary: "$500",
    references: "Restaurant Manager",
  },
  {
    applicant_name: "Binit Maharjan",
    applied_position: "Junior Frontend Developer",
    applicant_status: "Hired",
    tech_stack: "HTML, CSS, JavaScript",
    applicant_email: "binit@gmail.com",
    applicant_phone_number: "123456789",
    applicant_experience: "1.5 years",
    applicant_experience_level: "Junior",
    expected_salary: "$900",
    references: "Team Lead",
  },
  {
    applicant_name: "Sushank Gurung",
    applied_position: "React Developer",
    applicant_status: "Pending",
    tech_stack: "React, JavaScript, CSS",
    applicant_email: "sushank@gmail.com",
    applicant_phone_number: "12456789",
    applicant_experience: "2 years",
    applicant_experience_level: "Mid",
    expected_salary: "$1000",
    references: "John Doe",
  },
  {
    applicant_name: "Aryan Shrestha",
    applied_position: "Digital Marketing",
    applicant_status: "Interview Scheduled",
    tech_stack: "SEO, Google Ads",
    applicant_email: "aryan@gmail.com",
    applicant_phone_number: "12456789",
    applicant_experience: "1 year",
    applicant_experience_level: "Junior",
    expected_salary: "$800",
    references: "Jane Smith",
  },
  {
    applicant_name: "Alex Maharjan",
    applied_position: "MCdonnels Worker",
    applicant_status: "Rejected",
    tech_stack: "Customer Service",
    applicant_email: "alex@gmail.com",
    applicant_phone_number: "12456789",
    applicant_experience: "6 months",
    applicant_experience_level: "Entry",
    expected_salary: "$500",
    references: "Restaurant Manager",
  },
  {
    applicant_name: "Binit Maharjan",
    applied_position: "Junior Frontend Developer",
    applicant_status: "Hired",
    tech_stack: "HTML, CSS, JavaScript",
    applicant_email: "binit@gmail.com",
    applicant_phone_number: "123456789",
    applicant_experience: "1.5 years",
    applicant_experience_level: "Junior",
    expected_salary: "$900",
    references: "Team Lead",
  },
  {
    applicant_name: "Sushank Gurung",
    applied_position: "React Developer",
    applicant_status: "Pending",
    tech_stack: "React, JavaScript, CSS",
    applicant_email: "sushank@gmail.com",
    applicant_phone_number: "12456789",
    applicant_experience: "2 years",
    applicant_experience_level: "Mid",
    expected_salary: "$1000",
    references: "John Doe",
  },
  {
    applicant_name: "Aryan Shrestha",
    applied_position: "Digital Marketing",
    applicant_status: "Interview Scheduled",
    tech_stack: "SEO, Google Ads",
    applicant_email: "aryan@gmail.com",
    applicant_phone_number: "12456789",
    applicant_experience: "1 year",
    applicant_experience_level: "Junior",
    expected_salary: "$800",
    references: "Jane Smith",
  },
  {
    applicant_name: "Alex Maharjan",
    applied_position: "MCdonnels Worker",
    applicant_status: "Rejected",
    tech_stack: "Customer Service",
    applicant_email: "alex@gmail.com",
    applicant_phone_number: "12456789",
    applicant_experience: "6 months",
    applicant_experience_level: "Entry",
    expected_salary: "$500",
    references: "Restaurant Manager",
  },
  {
    applicant_name: "Binit Maharjan",
    applied_position: "Junior Frontend Developer",
    applicant_status: "Hired",
    tech_stack: "HTML, CSS, JavaScript",
    applicant_email: "binit@gmail.com",
    applicant_phone_number: "123456789",
    applicant_experience: "1.5 years",
    applicant_experience_level: "Junior",
    expected_salary: "$900",
    references: "Team Lead",
  },
  {
    applicant_name: "Sushank Gurung",
    applied_position: "React Developer",
    applicant_status: "Pending",
    tech_stack: "React, JavaScript, CSS",
    applicant_email: "sushank@gmail.com",
    applicant_phone_number: "12456789",
    applicant_experience: "2 years",
    applicant_experience_level: "Mid",
    expected_salary: "$1000",
    references: "John Doe",
  },
  {
    applicant_name: "Aryan Shrestha",
    applied_position: "Digital Marketing",
    applicant_status: "Interview Scheduled",
    tech_stack: "SEO, Google Ads",
    applicant_email: "aryan@gmail.com",
    applicant_phone_number: "12456789",
    applicant_experience: "1 year",
    applicant_experience_level: "Junior",
    expected_salary: "$800",
    references: "Jane Smith",
  },
  {
    applicant_name: "Alex Maharjan",
    applied_position: "MCdonnels Worker",
    applicant_status: "Rejected",
    tech_stack: "Customer Service",
    applicant_email: "alex@gmail.com",
    applicant_phone_number: "12456789",
    applicant_experience: "6 months",
    applicant_experience_level: "Entry",
    expected_salary: "$500",
    references: "Restaurant Manager",
  },
  {
    applicant_name: "Binit Maharjan",
    applied_position: "Junior Frontend Developer",
    applicant_status: "Hired",
    tech_stack: "HTML, CSS, JavaScript",
    applicant_email: "binit@gmail.com",
    applicant_phone_number: "123456789",
    applicant_experience: "1.5 years",
    applicant_experience_level: "Junior",
    expected_salary: "$900",
    references: "Team Lead",
  },
  {
    applicant_name: "Sushank Gurung",
    applied_position: "React Developer",
    applicant_status: "Pending",
    tech_stack: "React, JavaScript, CSS",
    applicant_email: "sushank@gmail.com",
    applicant_phone_number: "12456789",
    applicant_experience: "2 years",
    applicant_experience_level: "Mid",
    expected_salary: "$1000",
    references: "John Doe",
  },
  {
    applicant_name: "Aryan Shrestha",
    applied_position: "Digital Marketing",
    applicant_status: "Interview Scheduled",
    tech_stack: "SEO, Google Ads",
    applicant_email: "aryan@gmail.com",
    applicant_phone_number: "12456789",
    applicant_experience: "1 year",
    applicant_experience_level: "Junior",
    expected_salary: "$800",
    references: "Jane Smith",
  },
  {
    applicant_name: "Alex Maharjan",
    applied_position: "MCdonnels Worker",
    applicant_status: "Rejected",
    tech_stack: "Customer Service",
    applicant_email: "alex@gmail.com",
    applicant_phone_number: "12456789",
    applicant_experience: "6 months",
    applicant_experience_level: "Entry",
    expected_salary: "$500",
    references: "Restaurant Manager",
  },
  {
    applicant_name: "Binit Maharjan",
    applied_position: "Junior Frontend Developer",
    applicant_status: "Hired",
    tech_stack: "HTML, CSS, JavaScript",
    applicant_email: "binit@gmail.com",
    applicant_phone_number: "123456789",
    applicant_experience: "1.5 years",
    applicant_experience_level: "Junior",
    expected_salary: "$900",
    references: "Team Lead",
  },
  {
    applicant_name: "Sushank Gurung",
    applied_position: "React Developer",
    applicant_status: "Pending",
    tech_stack: "React, JavaScript, CSS",
    applicant_email: "sushank@gmail.com",
    applicant_phone_number: "12456789",
    applicant_experience: "2 years",
    applicant_experience_level: "Mid",
    expected_salary: "$1000",
    references: "John Doe",
  },
  {
    applicant_name: "Aryan Shrestha",
    applied_position: "Digital Marketing",
    applicant_status: "Interview Scheduled",
    tech_stack: "SEO, Google Ads",
    applicant_email: "aryan@gmail.com",
    applicant_phone_number: "12456789",
    applicant_experience: "1 year",
    applicant_experience_level: "Junior",
    expected_salary: "$800",
    references: "Jane Smith",
  },
  {
    applicant_name: "Alex Maharjan",
    applied_position: "MCdonnels Worker",
    applicant_status: "Rejected",
    tech_stack: "Customer Service",
    applicant_email: "alex@gmail.com",
    applicant_phone_number: "12456789",
    applicant_experience: "6 months",
    applicant_experience_level: "Entry",
    expected_salary: "$500",
    references: "Restaurant Manager",
  },
  {
    applicant_name: "Binit Maharjan",
    applied_position: "Junior Frontend Developer",
    applicant_status: "Hired",
    tech_stack: "HTML, CSS, JavaScript",
    applicant_email: "binit@gmail.com",
    applicant_phone_number: "123456789",
    applicant_experience: "1.5 years",
    applicant_experience_level: "Junior",
    expected_salary: "$900",
    references: "Team Lead",
  },
  {
    applicant_name: "Sushank Gurung",
    applied_position: "React Developer",
    applicant_status: "Pending",
    tech_stack: "React, JavaScript, CSS",
    applicant_email: "sushank@gmail.com",
    applicant_phone_number: "12456789",
    applicant_experience: "2 years",
    applicant_experience_level: "Mid",
    expected_salary: "$1000",
    references: "John Doe",
  },
  {
    applicant_name: "Aryan Shrestha",
    applied_position: "Digital Marketing",
    applicant_status: "Interview Scheduled",
    tech_stack: "SEO, Google Ads",
    applicant_email: "aryan@gmail.com",
    applicant_phone_number: "12456789",
    applicant_experience: "1 year",
    applicant_experience_level: "Junior",
    expected_salary: "$800",
    references: "Jane Smith",
  },
  {
    applicant_name: "Alex Maharjan",
    applied_position: "MCdonnels Worker",
    applicant_status: "Rejected",
    tech_stack: "Customer Service",
    applicant_email: "alex@gmail.com",
    applicant_phone_number: "12456789",
    applicant_experience: "6 months",
    applicant_experience_level: "Entry",
    expected_salary: "$500",
    references: "Restaurant Manager",
  },
  {
    applicant_name: "Binit Maharjan",
    applied_position: "Junior Frontend Developer",
    applicant_status: "Hired",
    tech_stack: "HTML, CSS, JavaScript",
    applicant_email: "binit@gmail.com",
    applicant_phone_number: "123456789",
    applicant_experience: "1.5 years",
    applicant_experience_level: "Junior",
    expected_salary: "$900",
    references: "Team Lead",
  },
  {
    applicant_name: "Sushank Gurung",
    applied_position: "React Developer",
    applicant_status: "Pending",
    tech_stack: "React, JavaScript, CSS",
    applicant_email: "sushank@gmail.com",
    applicant_phone_number: "12456789",
    applicant_experience: "2 years",
    applicant_experience_level: "Mid",
    expected_salary: "$1000",
    references: "John Doe",
  },
  {
    applicant_name: "Aryan Shrestha",
    applied_position: "Digital Marketing",
    applicant_status: "Interview Scheduled",
    tech_stack: "SEO, Google Ads",
    applicant_email: "aryan@gmail.com",
    applicant_phone_number: "12456789",
    applicant_experience: "1 year",
    applicant_experience_level: "Junior",
    expected_salary: "$800",
    references: "Jane Smith",
  },
  {
    applicant_name: "Alex Maharjan",
    applied_position: "MCdonnels Worker",
    applicant_status: "Rejected",
    tech_stack: "Customer Service",
    applicant_email: "alex@gmail.com",
    applicant_phone_number: "12456789",
    applicant_experience: "6 months",
    applicant_experience_level: "Entry",
    expected_salary: "$500",
    references: "Restaurant Manager",
  },
  {
    applicant_name: "Binit Maharjan",
    applied_position: "Junior Frontend Developer",
    applicant_status: "Hired",
    tech_stack: "HTML, CSS, JavaScript",
    applicant_email: "binit@gmail.com",
    applicant_phone_number: "123456789",
    applicant_experience: "1.5 years",
    applicant_experience_level: "Junior",
    expected_salary: "$900",
    references: "Team Lead",
  },
  {
    applicant_name: "Sushank Gurung",
    applied_position: "React Developer",
    applicant_status: "Pending",
    tech_stack: "React, JavaScript, CSS",
    applicant_email: "sushank@gmail.com",
    applicant_phone_number: "12456789",
    applicant_experience: "2 years",
    applicant_experience_level: "Mid",
    expected_salary: "$1000",
    references: "John Doe",
  },
  {
    applicant_name: "Aryan Shrestha",
    applied_position: "Digital Marketing",
    applicant_status: "Interview Scheduled",
    tech_stack: "SEO, Google Ads",
    applicant_email: "aryan@gmail.com",
    applicant_phone_number: "12456789",
    applicant_experience: "1 year",
    applicant_experience_level: "Junior",
    expected_salary: "$800",
    references: "Jane Smith",
  },
  {
    applicant_name: "Alex Maharjan",
    applied_position: "MCdonnels Worker",
    applicant_status: "Rejected",
    tech_stack: "Customer Service",
    applicant_email: "alex@gmail.com",
    applicant_phone_number: "12456789",
    applicant_experience: "6 months",
    applicant_experience_level: "Entry",
    expected_salary: "$500",
    references: "Restaurant Manager",
  },
  {
    applicant_name: "Binit Maharjan",
    applied_position: "Junior Frontend Developer",
    applicant_status: "Hired",
    tech_stack: "HTML, CSS, JavaScript",
    applicant_email: "binit@gmail.com",
    applicant_phone_number: "123456789",
    applicant_experience: "1.5 years",
    applicant_experience_level: "Junior",
    expected_salary: "$900",
    references: "Team Lead",
  },
  {
    applicant_name: "Sushank Gurung",
    applied_position: "React Developer",
    applicant_status: "Pending",
    tech_stack: "React, JavaScript, CSS",
    applicant_email: "sushank@gmail.com",
    applicant_phone_number: "12456789",
    applicant_experience: "2 years",
    applicant_experience_level: "Mid",
    expected_salary: "$1000",
    references: "John Doe",
  },
  {
    applicant_name: "Aryan Shrestha",
    applied_position: "Digital Marketing",
    applicant_status: "Interview Scheduled",
    tech_stack: "SEO, Google Ads",
    applicant_email: "aryan@gmail.com",
    applicant_phone_number: "12456789",
    applicant_experience: "1 year",
    applicant_experience_level: "Junior",
    expected_salary: "$800",
    references: "Jane Smith",
  },
  {
    applicant_name: "Alex Maharjan",
    applied_position: "MCdonnels Worker",
    applicant_status: "Rejected",
    tech_stack: "Customer Service",
    applicant_email: "alex@gmail.com",
    applicant_phone_number: "12456789",
    applicant_experience: "6 months",
    applicant_experience_level: "Entry",
    expected_salary: "$500",
    references: "Restaurant Manager",
  },
  {
    applicant_name: "Binit Maharjan",
    applied_position: "Junior Frontend Developer",
    applicant_status: "Hired",
    tech_stack: "HTML, CSS, JavaScript",
    applicant_email: "binit@gmail.com",
    applicant_phone_number: "123456789",
    applicant_experience: "1.5 years",
    applicant_experience_level: "Junior",
    expected_salary: "$900",
    references: "Team Lead",
  },
  {
    applicant_name: "Sushank Gurung",
    applied_position: "React Developer",
    applicant_status: "Pending",
    tech_stack: "React, JavaScript, CSS",
    applicant_email: "sushank@gmail.com",
    applicant_phone_number: "12456789",
    applicant_experience: "2 years",
    applicant_experience_level: "Mid",
    expected_salary: "$1000",
    references: "John Doe",
  },
  {
    applicant_name: "Aryan Shrestha",
    applied_position: "Digital Marketing",
    applicant_status: "Interview Scheduled",
    tech_stack: "SEO, Google Ads",
    applicant_email: "aryan@gmail.com",
    applicant_phone_number: "12456789",
    applicant_experience: "1 year",
    applicant_experience_level: "Junior",
    expected_salary: "$800",
    references: "Jane Smith",
  },
  {
    applicant_name: "Alex Maharjan",
    applied_position: "MCdonnels Worker",
    applicant_status: "Rejected",
    tech_stack: "Customer Service",
    applicant_email: "alex@gmail.com",
    applicant_phone_number: "12456789",
    applicant_experience: "6 months",
    applicant_experience_level: "Entry",
    expected_salary: "$500",
    references: "Restaurant Manager",
  },
  {
    applicant_name: "Binit Maharjan",
    applied_position: "Junior Frontend Developer",
    applicant_status: "Hired",
    tech_stack: "HTML, CSS, JavaScript",
    applicant_email: "binit@gmail.com",
    applicant_phone_number: "123456789",
    applicant_experience: "1.5 years",
    applicant_experience_level: "Junior",
    expected_salary: "$900",
    references: "Team Lead",
  },
  {
    applicant_name: "Sushank Gurung",
    applied_position: "React Developer",
    applicant_status: "Pending",
    tech_stack: "React, JavaScript, CSS",
    applicant_email: "sushank@gmail.com",
    applicant_phone_number: "12456789",
    applicant_experience: "2 years",
    applicant_experience_level: "Mid",
    expected_salary: "$1000",
    references: "John Doe",
  },
  {
    applicant_name: "Aryan Shrestha",
    applied_position: "Digital Marketing",
    applicant_status: "Interview Scheduled",
    tech_stack: "SEO, Google Ads",
    applicant_email: "aryan@gmail.com",
    applicant_phone_number: "12456789",
    applicant_experience: "1 year",
    applicant_experience_level: "Junior",
    expected_salary: "$800",
    references: "Jane Smith",
  },
];
